#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)" 
APP_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

source "$APP_DIR/.env"

mkdir -p "$UPLOAD_LOCATION"

docker compose -f "$APP_DIR/compose.yml" -d
